// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjznrkmxbjkjbqvcyivb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqem5ya214YmpramJxdmN5aXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTk5ODAsImV4cCI6MjA2NDA5NTk4MH0.zjYagUQVcYkFP_ApITbsxO99j7xBuMfsRJZzNVU4ioc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);